# Generated by Django 4.2.27 on 2025-12-25 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_sitecounter_alter_articlepost_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlepost',
            name='total_views',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
